### ISSUE TITLE
java.io.IOException: Stream closed error 

### ISSUE THREAD

**Issue by viswanathareddy04** [fracpete/rsync4j#2]
Copying resource 'com/github/fracpete/rsync4j/windows-x86_64/cygcom_err-2.dll' to 'C:\Users\XXXXXXXXX\rsync4j\bin\cygcom_err-2.dll'
com.github.fracpete.rsync4j.Binaries     : Copying failed!

java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:159) ~[na:1.8.0_121]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_121]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[na:1.8.0_121]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[na:1.8.0_121]
	at java.io.FilterInputStream.read(FilterInputStream.java:107) ~[na:1.8.0_121]
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1719) ~[commons-io-2.3.jar!/:2.3]
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1696) ~[commons-io-2.3.jar!/:2.3]
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1671) ~[commons-io-2.3.jar!/:2.3]
	at com.github.fracpete.rsync4j.Binaries.copyResourceTo(Binaries.java:114) [rsync4j-3.1.2-5.jar!/:na]
	at com.github.fracpete.rsync4j.Binaries.extractBinaries(Binaries.java:173) [rsync4j-3.1.2-5.jar!/:na]
	at com.github.fracpete.rsync4j.Binaries.rsyncBinary(Binaries.java:210) [rsync4j-3.1.2-5.jar!/:na]
	at com.github.fracpete.rsync4j.RSync.commandLineArgs(RSync.java:1752) [rsync4j-3.1.2-5.jar!/:na]
  

Using Windows Server 2008 ,64 bit

**Comment by fracpete** [comment]
Not sure why this if failing in your case.
Just tried successfully the following command-line as admin and regular user on Windows 10 64bit:
```
C:\Users\rsync-test\Downloads\rsync4j-3.1.2-5\lib>java -cp ".\*" com.github.fracpete.rsync4j.RSync -r C:\Users\rsync-test\Downloads\weka-3-8-2 C:\Users\rsync-test\Downloads\weka-3-8-2-test\
```
**NB:** I downloaded a Weka release zip file and extracted it only to have something to copy recursively.

More details about user, command-line, java-version?

**Comment by viswanathareddy04** [comment]
We are getting this error while copying the dlls to home directory 
Tried both as admin and non-admin user, Java version is 1.8 and I have added your maven dependency and tried using Rsync class

**Comment by fracpete** [comment]
Are any DLLs/executables copied into the `C:\Users\XXXXXXXXX\rsync4j\bin` directory at all? I'm on Linux and don't access to Windows Server, to see whether there is something funny going on with the permissions in your home directories. Are group policies prohibiting copying files in there? If you copy all the DLLs/executables (see [here](https://github.com/fracpete/rsync4j#binaries)) manually into a directory in your home directory, can you then execute the `rsync.exe` executable?

**Comment by viswanathareddy04** [comment]
they are being copied but with 0-byte size.Yeah after copying them manually, I can execute the rsync.exe.

**Comment by fracpete** [comment]
Seems odd that you can copy them manually, but it fails when the process launched by your user can't. What are the permissions for that directory?

**Comment by fracpete** [comment]
Managed to get access to a Windows Server 2012 R2 machine. Worked just fine. So not just sure what the problem is on your machine.
However, I've made a new release which allows you to specify on Windows the rsync4j home directory via the `RSYNC4J_HOME` environment variable. That way, you should be able to set up a directory with correct permissions and then just use rsync4j as is, without manual copying of files.

**Comment by viswanathareddy04** [comment]
Thank you, But this didn't help too.  Same issue not able to copy the binaries.
Copying failed!

java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:159) ~[na:1.8.0_144]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_144]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[na:1.8.0_144]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[na:1.8.0_144]
	at java.io.FilterInputStream.read(FilterInputStream.java:107) ~[na:1.8.0_144]
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1719) ~[commons-io-2.3.jar!/:2.3]
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1696) ~[commons-io-2.3.jar!/:2.3]
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1671) ~[commons-io-2.3.jar!/:2.3]
	at com.github.fracpete.rsync4j.Binaries.copyResourceTo(Binaries.java:117) [rsync4j-3.1.2-6.jar!/:na]
	at com.github.fracpete.rsync4j.Binaries.extractBinaries(Binaries.java:200) [rsync4j-3.1.2-6.jar!/:na]
	at com.github.fracpete.rsync4j.Binaries.rsyncBinary(Binaries.java:237) [rsync4j-3.1.2-6.jar!/:na]
	at com.github.fracpete.rsync4j.RSync.commandLineArgs(RSync.java:1752) [rsync4j-3.1.2-6.jar!/:na]

**Comment by fracpete** [comment]
Did you create the directory beforehand? What are the permissions of the generated directory? Since I cannot replicate this issue on the Windows installations that I have access to, there isn't much I can do.

**Comment by fracpete** [comment]
BTW Are you using Oracle's Java 1.8?

**Comment by viswanathareddy04** [comment]
I have tried both ways, creating directory beforehand and running the rsync. and let rsync create the folder.both ways it failed. Yeah I'm using Oracles Java 1.8 . 

I'm running this from a Jar file. I have your Maven dependency in my pom . from the jar file I'm getting this error when its trying to copy. Sorry if I didn't mention this earlier.

**Comment by fracpete** [comment]
What are the effective permissions on that directory?

**Comment by viswanathareddy04** [comment]
The user has Admin Access with full control over the system.

**Comment by fracpete** [comment]
Do you have the same permissions like this:
![security](https://user-images.githubusercontent.com/1026180/34795356-e9f7c44a-f6b6-11e7-8e86-29378c0b1e7b.png)

**Comment by viswanathareddy04** [comment]
Yeah , Correct. I have the same permission. Have you tried this Rsync running from a Jar file?

**Comment by fracpete** [comment]
I used the rsync4j artifact successfully in a Windows 64bit production machine without any problems (as part of a larger project). On the Windows 2012 Server machine, used the command-line that I [posted earlier](https://github.com/fracpete/rsync4j/issues/2#issuecomment-355120767).

**Comment by viswanathareddy04** [comment]
Great, I'm not sure what the issue is. I have forked your project and I'll try making changes to it. I'll update you if that works. Thanks for your help.

**Comment by fracpete** [comment]
Yes, it's really bizarre... Did the command-line that I posted actually work for you? Also, how do you build your final jar: are you using a shader plugin or something similar to create just a single jar?

**Comment by viswanathareddy04** [comment]
When I run your project as standalone with the main method, It worked fine. I'm building jar using Jenkins. Which isn't working.

**Comment by fracpete** [comment]
Jenkins won't be the issues as I use that as well. Does your final jar contain all dependencies as nested jars or do you unzip all dependencies into the final jar?

**Comment by viswanathareddy04** [comment]
My final jar contains all dependencies as a nested jar.

**Comment by fracpete** [comment]
That being the only difference, this must the issue then.

**Comment by fracpete** [comment]
In the `Binaries` class, change line 112 to this:
```java
      is  = Binaries.class.getClassLoader().getResourceAsStream(resource);
```
Does that fix your problem?
Based on [this answer](https://stackoverflow.com/a/1900173/4698227) on stackoverflow.

**Comment by viswanathareddy04** [comment]
Can you make a release of the above change? I have tested locally (not from jar) it works as like the old one. If you can update it, I can directly include the above maven dependency

**Comment by fracpete** [comment]
Also successfully tested it from a jar generated by `spring-boot-maven-plugin`, which includes all its dependencies within an executable jar. Just made a new release: [3.1.2-7](https://github.com/fracpete/rsync4j/releases/tag/rsync4j-3.1.2-7)
Thanks for your help in sorting this out.
